name: .NET

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

env:
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API }}
  VERSION_STATIC: 0.1.${{ github.run_number }}-beta

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        mkdir __out
        dotnet pack --no-restore -o __out -p:PackageVersion=${VERSION_STATIC}
        dotnet nuget push "__out/*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API}}
