name: .NET

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

env:
  NUGET_KEY: ${{ secrets.NUGET_API }}
  VERSION_STATIC: 0.1.${{ github.run_number }}-beta

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        mkdir __out
        dotnet pack --no-restore -o __out -p:PackageVersion=$VERSION_STATIC
        dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key $NUGET_KEY
    
    # - name: Publish CG4.Benchmark.Tests
    #   uses: rohith/publish-nuget@v2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Benchmark.Tests/CG4.Benchmark.Tests.csproj


    # - name: Publish CG4.DataAccess
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.DataAccess/CG4.DataAccess.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Executor
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Executor/CG4.Executor.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Executor.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Executor.Tests/CG4.Executor.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Extensions
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Extensions/CG4.Extensions.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Extensions.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Extensions.Tests/CG4.Extensions.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Dapper
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Dapper/CG4.Impl.Dapper.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Dapper.PostgreSql
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Dapper.PostgreSql/CG4.Impl.Dapper.PostgreSql.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.EF
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.EF/CG4.Impl.EF.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.EF.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.EF.Tests/CG4.Impl.EF.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.ElasticSearch
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.ElasticSearch/CG4.Impl.ElasticSearch.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Kafka
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Kafka/CG4.Impl.Kafka.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Memory
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Memory/CG4.Impl.Memory.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Memory.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Memory.Tests/CG4.Impl.Memory.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.MongoDB
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.MongoDB/CG4.Impl.MongoDB.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.MongoDB.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.MongoDB.Tests/CG4.Impl.MongoDB.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Prometheus
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Prometheus/CG4.Impl.Prometheus.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Rabbit
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Rabbit/CG4.Impl.Rabbit.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.Impl.Rabbit.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.Impl.Rabbit.Tests/CG4.Impl.Rabbit.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.SqlBuilder.Benchmark.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.SqlBuilder.Benchmark.Tests/CG4.SqlBuilder.Benchmark.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta

    # - name: Publish CG4.SqlBuilder.Tests
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #       PROJECT_FILE_PATH: src/CG4.SqlBuilder.Tests/CG4.SqlBuilder.Tests.csproj
    #       NUGET_KEY: ${{ secrets.NUGET_API }}
    #       VERSION_STATIC: 0.1.${{ github.run_number }}-beta
